import type {Metadata,Viewport} from 'next';
import {Instrument_Serif,Manrope} from 'next/font/google';
import './globals.css';
import './video-responsive.css';
import Script from 'next/script';
import PageViewTracker from '@/components/PageViewTracker';
const displayFont=Instrument_Serif({subsets:['latin'],weight:'400',style:['normal','italic'],variable:'--font-display',display:'swap'});
const bodyFont=Manrope({subsets:['latin'],weight:['400','500','600','700','800'],variable:'--font-body',display:'swap'});
const ogImage='https://res.cloudinary.com/m71breje/image/upload/w_1200,h_630,c_fill,g_auto,q_auto/v1786171381/panquecitos_sin_logo_i59l6l.jpg';
export const metadata:Metadata={title:'Club BASA Acapulco | Panquecitos, waffles, crepas y malteadas',description:'Catálogo interactivo de Club BASA Acapulco. Panquecitos, waffles, crepas, malteadas, té, aloe y más. Pide fácil por WhatsApp.',metadataBase:new URL(process.env.NEXT_PUBLIC_SITE_URL||'https://menu.club-basa.com'),manifest:'/manifest.json',appleWebApp:{capable:true,statusBarStyle:'default',title:'Club BASA'},openGraph:{title:'Club BASA Acapulco',description:'Sabor que enamora. Nutrición que acompaña.',type:'website',images:[{url:ogImage,width:1200,height:630,alt:'Six de panquecitos Club BASA Acapulco'}]},twitter:{card:'summary_large_image',title:'Club BASA Acapulco',description:'Sabor que enamora. Nutrición que acompaña.',images:[ogImage]},robots:{index:true,follow:true}};
export const viewport:Viewport={themeColor:'#f5820b'};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="es-MX" className={`${displayFont.variable} ${bodyFont.variable}`} suppressHydrationWarning><head><script dangerouslySetInnerHTML={{__html:"try{var t=localStorage.getItem('clubbasa-theme');if(t==='dark'||t==='light')document.documentElement.setAttribute('data-theme',t);}catch(e){}"}}/></head><body>{children}<PageViewTracker/>{process.env.NEXT_PUBLIC_GA_ID&&<><Script src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`} strategy="afterInteractive"/><Script id="ga4" strategy="afterInteractive">{`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${process.env.NEXT_PUBLIC_GA_ID}',{anonymize_ip:true});`}</Script></>}</body></html>}