import type {Metadata} from 'next';
import {Instrument_Serif,Manrope} from 'next/font/google';
import './globals.css';
import './video-responsive.css';
import Script from 'next/script';
import PageViewTracker from '@/components/PageViewTracker';
const displayFont=Instrument_Serif({subsets:['latin'],weight:'400',style:['normal','italic'],variable:'--font-display',display:'swap'});
const bodyFont=Manrope({subsets:['latin'],weight:['400','500','600','700','800'],variable:'--font-body',display:'swap'});
export const metadata:Metadata={title:'Club BASA Acapulco | Panquecitos, waffles, crepas y malteadas',description:'Catálogo interactivo de Club BASA Acapulco. Panquecitos, waffles, crepas, malteadas, té, aloe y más. Pide fácil por WhatsApp.',metadataBase:new URL(process.env.NEXT_PUBLIC_SITE_URL||'https://menu.club-basa.com'),openGraph:{title:'Club BASA Acapulco',description:'Sabor que enamora. Nutrición que transforma.',type:'website'},robots:{index:true,follow:true}};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="es-MX" className={`${displayFont.variable} ${bodyFont.variable}`}><body>{children}<PageViewTracker/><Script id="product-cart-add-flow" strategy="afterInteractive">{`document.addEventListener('click',function(event){const el=event.target instanceof Element?event.target.closest('.productModalAdd'):null;if(!el)return;window.setTimeout(function(){const close=document.querySelector('.productModalClose');if(close)close.click();const cart=document.querySelector('.cart');if(cart)cart.scrollIntoView({behavior:'smooth',block:'center'});},0);});`}</Script>{process.env.NEXT_PUBLIC_GA_ID&&<><Script src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`} strategy="afterInteractive"/><Script id="ga4" strategy="afterInteractive">{`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${process.env.NEXT_PUBLIC_GA_ID}',{anonymize_ip:true});`}</Script></>}</body></html>}